# The name of the environment variable which will store the bot token.
Token Env Var: DnDToken

# Command prefix for all commands.
Prefix: '!'

# The channel ID of the channel taht the bot will send messages to.
Log Channel: 708470952345731093

# The ID of the user you want to be pinged by the Broken command.
Broken User ID: 246669108752416768

# Sets the 'Playing' status of the bot.
Game Status:
  # 'true' will display 'Playing ___' (___ set below), 'false' won't display anything.
  Active: true

  # The game activity to display.
  # NOTE: Use '{prefix}' as a placeholder for the bots command prefix.
  # Default: '{prefix}help'
  Game: '{prefix}help'

# Settings that will apply to almost every embedded message unless specified otherwise.
Embed Settings:
  # The color of the sidebar for embedded messages, in RGB standard.
  Color:
    r: 254
    g: 254
    b: 254

  # This option will delete the user's message after they send a command.
  # NOTE: The bot needs "manage messages" permission for this to work.
  Delete Commands: false

  # Whether or not to show the author of every command in the response given.
  # NOTE: Works well with the "Delete Commands" option above.
  Show Author: true

  Footer:
    # The text for the footer of the messages.
    Text: DnD Gang

    # The url for the icon at the bottom of your footer image.
    Icon URL: https://cdn.discordapp.com/icons/711784408536973383/f5bdf3bdf170a3c4d0cc773dec138047.png

# The link for the server invite.
Server Invite: https://discordapp.com/abcabc

# The text for the online log message.
# NOTE: Use '{username}' as a placeholder for the bot's username.
Online Message: '{username} Online!'

# The text for the restarting log message.
# NOTE: Use '{username}' as a placeholder for the bot's username.
Restarting Message: '{username} Restarting...'

# The file where data gets stored. Probably shouldn't mess with this.
Data File: ./Data/data_storage.json
